import { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Bell, ChevronDown, Menu, MapPin } from 'lucide-react';
import { useAuth } from '@/providers/AuthProvider';
import { useWorkspace } from '@/providers/WorkspaceProvider';
import type { DemoRole } from './Sidebar';

const pageTitles: Record<string, string> = { '/overview': 'Overview', '/my-location': 'My location', '/monitoring/alerts': 'Alert center', '/locations': 'Locations', '/content': 'Content', '/campaigns': 'Campaigns', '/schedule': 'Schedule', '/reports': 'Reports', '/team': 'Team & Roles', '/settings': 'Settings', '/help': 'Help & Support', '/access-denied': 'Access denied', '/not-found': 'Page not found' };
const roleLabels: Record<DemoRole, string> = { owner: 'Organization Owner', marketing: 'Marketing Manager', operations: 'Operations Manager', branch: 'Branch Manager', viewer: 'Viewer' };
export function TopBar({ role, onMenuOpen, alertCount = 0 }: { role: DemoRole; onMenuOpen: () => void; alertCount?: number }) {
  const location = useLocation(); const navigate = useNavigate(); const { user } = useAuth(); const { workspace } = useWorkspace(); const [scopeOpen, setScopeOpen] = useState(false);
  const name = user?.user_metadata?.full_name || user?.email?.split('@')[0] || 'User'; const initials = name.split(/\s+/).map((part: string) => part[0]).join('').slice(0, 2).toUpperCase(); const scope = role === 'branch' ? workspace?.name ?? 'My location' : 'All locations';
  return <header style={{ height: 'var(--topbar-height)', background: 'var(--surface)', borderBottom: '1px solid var(--border-color)', display: 'flex', alignItems: 'center', paddingInline: 24, gap: 16, flexShrink: 0, position: 'sticky', top: 0, zIndex: 50 }}><button onClick={onMenuOpen} className="mobile-menu-btn" aria-label="Open navigation" style={{ display: 'none', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink-secondary)', padding: 6 }}><Menu size={20}/></button><h1 style={{ flex: 1, fontSize: 16, fontWeight: 600, color: 'var(--ink)', margin: 0 }}>{pageTitles[location.pathname] ?? 'BranchCast'}</h1><div className="scope-selector" style={{ position: 'relative' }}><button onClick={() => setScopeOpen(p => !p)} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '6px 10px', border: '1px solid var(--border-color)', borderRadius: 8, background: 'var(--surface)', color: 'var(--ink-secondary)', fontSize: 13, cursor: 'pointer' }}><MapPin size={14}/><span>{scope}</span><ChevronDown size={14}/></button>{scopeOpen && <div style={{ position: 'absolute', top: '100%', right: 0, marginTop: 4, background: 'var(--surface)', border: '1px solid var(--border-color)', borderRadius: 10, boxShadow: 'var(--shadow-md)', zIndex: 100, minWidth: 200, padding: 8 }}><button onClick={() => setScopeOpen(false)} style={{ width: '100%', textAlign: 'left', padding: 9, border: 0, background: 'var(--surface-subtle)', color: 'var(--ink)', cursor: 'pointer' }}>{scope}</button></div>}</div><span className="date-context" style={{ fontSize: 13, color: 'var(--ink-tertiary)', whiteSpace: 'nowrap' }}>{new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date())}</span><button onClick={() => navigate('/monitoring/alerts')} aria-label={`Notifications — ${alertCount} unresolved`} style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'center', width: 36, height: 36, background: 'none', border: 'none', borderRadius: 8, cursor: 'pointer', color: alertCount > 0 ? 'var(--ink)' : 'var(--ink-tertiary)' }}><Bell size={18}/>{alertCount > 0 && <span style={{ position: 'absolute', top: 4, right: 4, width: 8, height: 8, background: 'var(--danger)', borderRadius: '50%', border: '1.5px solid var(--surface)' }}/>}</button><button aria-label={`${name} — ${roleLabels[role]}`} style={{ width: 34, height: 34, borderRadius: '50%', background: 'var(--signal)', color: '#fff', fontSize: 12, fontWeight: 600, border: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>{initials}</button><style>{'@media(max-width:767px){.mobile-menu-btn{display:flex!important}.date-context,.scope-selector{display:none!important}}'}</style></header>;
}
