import { useState, type FormEvent } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
export function AuthPage({ mode }: { mode: 'login' | 'signup' }) {
  const navigate = useNavigate(); const location = useLocation(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault(); if(!supabase)return; setBusy(true);setMessage(''); const redirectTo=`${window.location.origin}/onboarding`; const r=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:redirectTo}}); setBusy(false); if(r.error){setMessage(r.error.message);return;} if(mode==='signup' && !r.data.session){setMessage('Check your email to confirm your account, then return here to log in.');return;} navigate((location.state as {from?:string})?.from ?? (mode==='signup'?'/onboarding':'/overview'));};
  return <div style={{ minHeight:'100vh', display:'grid', gridTemplateColumns:'1fr 1fr', background:'var(--canvas)' }}><aside style={{ background:'#211C18', color:'#fff', padding:48, display:'flex', flexDirection:'column', justifyContent:'space-between' }}><Link to="/" style={{color:'#fff',textDecoration:'none',fontSize:20,fontWeight:700}}>Branch<span style={{color:'var(--signal)'}}>Cast</span></Link><div><p style={{color:'var(--signal)',fontSize:13,fontWeight:600}}>YOUR BUSINESS, IN SYNC</p><h1 style={{fontSize:44,lineHeight:1.05,letterSpacing:'-.04em'}}>Audio operations, made clear.</h1></div><span style={{color:'rgba(255,255,255,.45)',fontSize:13}}>Built for multi-location teams.</span></aside><main style={{display:'grid',placeItems:'center',padding:28}}><form onSubmit={submit} style={{width:'min(100%,420px)',background:'#fff',border:'1px solid var(--border-color)',borderRadius:18,padding:32,boxShadow:'var(--shadow-md)'}}><h2 style={{margin:0,fontSize:28}}>{mode==='login'?'Welcome back':'Create your workspace'}</h2><p style={{color:'var(--ink-secondary)',margin:'8px 0 24px'}}>{mode==='login'?'Log in to manage your audio network.':'Start as the organization owner. You will add your first branch next.'}</p>{mode==='signup'&&<label style={{display:'block',fontSize:13,fontWeight:600,marginBottom:14}}>Your name<input required value={name} onChange={e=>setName(e.target.value)} style={inputStyle}/></label>}<label style={{display:'block',fontSize:13,fontWeight:600,marginBottom:14}}>Work email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} style={inputStyle}/></label><label style={{display:'block',fontSize:13,fontWeight:600}}>Password<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} style={inputStyle}/></label>{message&&<p style={{fontSize:13,color:message.startsWith('Check')?'var(--success)':'var(--danger)',lineHeight:1.45}}>{message}</p>}<button disabled={busy} style={{width:'100%',marginTop:22,border:0,borderRadius:8,padding:'12px 14px',background:'var(--signal)',color:'#fff',fontWeight:600,cursor:'pointer'}}>{busy?'Please wait…':mode==='login'?'Log in':'Create account'}</button><p style={{fontSize:13,color:'var(--ink-secondary)',marginBottom:0,textAlign:'center'}}>{mode==='login'?'New to BranchCast? ':'Already have an account? '}<Link to={mode==='login'?'/signup':'/login'} style={{color:'var(--signal)',fontWeight:600}}>{mode==='login'?'Create a workspace':'Log in'}</Link></p></form></main></div>;
}
const inputStyle={width:'100%',marginTop:6,padding:'11px 12px',border:'1px solid var(--border-color)',borderRadius:8,font:'inherit',outline:'none',background:'#fff'} as const;
