import { useEffect, useState } from 'react';
import { Check, CreditCard, RefreshCw } from 'lucide-react';
import { useWorkspace } from '@/providers/WorkspaceProvider';
import { supabase } from '@/lib/supabase';
type Subscription = { plan_key: string; status: string; provider: string; current_period_end: string | null; cancel_at_period_end: boolean };
const db = supabase as any;
const plans = [{ key: 'starter', name: 'Starter', features: ['1 location', 'Core scheduling', 'Basic monitoring'] }, { key: 'growth', name: 'Growth', features: ['Multiple locations', 'Campaigns and reports', 'Priority support'] }, { key: 'enterprise', name: 'Enterprise', features: ['Unlimited locations', 'Advanced roles and audit', 'Dedicated onboarding'] }];
export function BillingPage() { const { workspace } = useWorkspace(); const [subscription, setSubscription] = useState<Subscription | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); useEffect(() => { if (!db || !workspace) return; void db.from('billing_subscriptions').select('plan_key,status,provider,current_period_end,cancel_at_period_end').eq('organization_id', workspace.id).maybeSingle().then((result: any) => { setSubscription(result.data as Subscription | null); setMessage(result.error?.message ?? ''); setLoading(false); }); }, [workspace?.id]); return <div style={page}><header><p style={eyebrow}>WORKSPACE SETTINGS</p><h1 style={title}>Plans & billing</h1><p style={sub}>Subscription state is synchronized from the billing provider webhook.</p></header><section style={current}><span style={currentIcon}><CreditCard size={20}/></span><div><strong>{workspace?.name ?? 'Your workspace'}</strong><p style={sub}>{loading ? 'Loading subscription…' : `Current plan: ${subscription?.plan_key ?? 'trial'} · Status: ${subscription?.status ?? 'trialing'}`}</p></div><button style={button} onClick={() => window.location.reload()}><RefreshCw size={14}/> Refresh</button></section>{message && <p style={{ color: 'var(--danger)' }}>{message}</p>}<div style={grid}>{plans.map(plan => <article style={{ ...card, ...(subscription?.plan_key === plan.key ? featured : {}) }} key={plan.key}><h2>{plan.name}</h2><ul>{plan.features.map(feature => <li key={feature}><Check size={15}/> {feature}</li>)}</ul><span style={subscription?.plan_key === plan.key ? active : secondary}>{subscription?.plan_key === plan.key ? 'Current plan' : 'Contact administrator'}</span></article>)}</div></div>; }
const page = { padding: '32px 40px', maxWidth: 1100, margin: '0 auto' } as const; const eyebrow = { margin: 0, color: 'var(--signal)', fontWeight: 600, fontSize: 12, letterSpacing: '.06em' } as const; const title = { margin: '5px 0', fontSize: 28 } as const; const sub = { margin: 0, color: 'var(--ink-secondary)' } as const; const current = { display: 'flex', alignItems: 'center', gap: 14, background: 'var(--surface-subtle)', borderRadius: 14, padding: 18, margin: '26px 0' } as const; const currentIcon = { width: 38, height: 38, display: 'grid', placeItems: 'center', borderRadius: 10, background: '#fff', color: 'var(--signal)' } as const; const button = { marginLeft: 'auto', display: 'inline-flex', alignItems: 'center', gap: 6, border: '1px solid var(--border-color)', borderRadius: 8, padding: '8px 10px', background: '#fff', cursor: 'pointer' } as const; const grid = { display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 14 } as const; const card = { background: '#fff', border: '1px solid var(--border-color)', borderRadius: 14, padding: 22 } as const; const featured = { border: '2px solid var(--signal)' } as const; const active = { display: 'inline-block', color: 'var(--success)', fontSize: 12, fontWeight: 600 } as const; const secondary = { display: 'inline-block', color: 'var(--ink-secondary)', fontSize: 12 } as const;
