import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { CheckCircle2, LogOut, Pause, Play, Radio, RefreshCw, Square, Wifi } from 'lucide-react';
import { supabase } from '@/lib/supabase';
type Player={id:string;display_name:string|null;state:string};type Session={token:string;player:Player};const KEY='branchcast.browser-player-session';
export function BrowserPlayerRevamp(){const [code,setCode]=useState('');const [session,setSession]=useState<Session|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [lastHeartbeat,setLastHeartbeat]=useState('');const [track,setTrack]=useState('No audio selected');const [playing,setPlaying]=useState(false);const audio=useState(()=>new Audio())[0];
 const call=useCallback(async(name:string,body:Record<string,unknown>)=>{const res=await supabase.functions.invoke(name,{body});if(res.error)throw new Error(res.error.message);return res.data as Record<string,any>},[]);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setSession(JSON.parse(raw))}catch{localStorage.removeItem(KEY)}},[]);
 const enable=async()=>{try{const c=new AudioContext();await c.resume();await c.close();setMessage('Audio is enabled for this browser.')}catch{setError('Tap Enable audio once, then try playback again.')}};
 const pair=async(e:FormEvent)=>{e.preventDefault();if(!code.trim())return;setBusy(true);setError('');try{const data=await call('player-pair',{pairing_code:code.trim().toUpperCase(),agent_version:'browser/2.0'});const next={token:data.browser_session_token,player:data.player as Player};localStorage.setItem(KEY,JSON.stringify(next));setSession(next);setCode('');setMessage('Player connected. This browser is now the player.')}catch(err){setError(err instanceof Error?err.message:'Pairing failed.')}finally{setBusy(false)}};
 const heartbeat=useCallback(async()=>{if(!session)return;try{await call('player-browser-heartbeat',{session_token:session.token,state:'online'});setLastHeartbeat(new Date().toLocaleTimeString());setError('')}catch(err){setError(err instanceof Error?err.message:'Heartbeat failed.')}},[call,session]);
 useEffect(()=>{if(!session)return;void heartbeat();const t=window.setInterval(()=>void heartbeat(),10000);return()=>window.clearInterval(t)},[heartbeat,session]);
 useEffect(()=>{if(!session)return;const poll=async()=>{try{const data=await call('player-browser-runtime',{session_token:session.token,action:'poll'});const command=data.command as {id:string;command:string;payload?:{audio_url?:string;title?:string}}|null;if(!command)return;if(command.command==='play'){if(!command.payload?.audio_url)throw new Error('Waiting for the manager playlist.');if(audio.src!==command.payload.audio_url){audio.src=command.payload.audio_url;audio.load()}await audio.play();setTrack(command.payload.title??'Audio asset')}else if(command.command==='pause')audio.pause();else if(command.command==='stop'){audio.pause();audio.currentTime=0;setTrack('No audio selected')}else if(command.command==='skip'){audio.pause();audio.currentTime=0;setTrack('No audio selected')}setMessage(`Command completed: ${command.command}`);await call('player-browser-runtime',{session_token:session.token,action:'ack',command_id:command.id,status:'acknowledged'})}catch(err){setError(err instanceof Error?err.message:'Runtime connection failed.')} };void poll();const t=window.setInterval(()=>void poll(),4000);return()=>window.clearInterval(t)},[audio,call,session]);
 useEffect(()=>{const onPlay=()=>setPlaying(true);const onPause=()=>setPlaying(false);audio.addEventListener('play',onPlay);audio.addEventListener('pause',onPause);return()=>{audio.pause();audio.removeEventListener('play',onPlay);audio.removeEventListener('pause',onPause)}},[audio]);
 const localPlay=async()=>{if(!audio.src){setError('Waiting for the manager playlist. Start playback from Manager Playback first.');return}await enable();try{await audio.play()}catch{setError('Tap Enable audio, then press Play again.')}};const localPause=()=>audio.pause();const localStop=()=>{audio.pause();audio.currentTime=0;setTrack('No audio selected')};const disconnect=()=>{audio.pause();localStorage.removeItem(KEY);setSession(null);setMessage('Browser player disconnected.')};
 if(!session)return <main className="browser-player-shell"><section className="browser-pair-card"><div className="browser-brand">Branch<span>Cast</span></div><span className="browser-icon"><Radio size={28}/></span><p className="design-eyebrow">BROWSER PLAYER</p><h1>Connect this browser</h1><p>Open this page on the desktop or mobile browser that should play this branch’s audio. Enter the pairing code from the manager’s Location page.</p><form onSubmit={pair}><label>Pairing code<input autoFocus value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="e.g. 7E35ED" maxLength={12}/></label>{error&&<span className="design-error">{error}</span>}<button className="design-primary" disabled={busy||!code.trim()}>{busy?'Connecting…':'Connect browser player'}</button></form><small>This page does not require a manager login. Keep this tab open while the player is running.</small></section></main>;
 return <main className="browser-player-shell"><section className="browser-live-card"><div className="browser-card-head"><div className="browser-brand">Branch<span>Cast</span></div><span className="live-pill">LIVE</span></div><span className="browser-icon connected"><Wifi size={28}/></span><p className="design-eyebrow">BROWSER PLAYER</p><h1>{session.player.display_name??'District 7 player'}</h1><p>This browser is connected and sending its heartbeat to BranchCast.</p><div className="browser-status"><CheckCircle2 size={17}/><span>Connected · last heartbeat {lastHeartbeat||'connecting…'}</span></div><div className="browser-track"><span>{playing?<Play size={16}/>:<Pause size={16}/>}</span><div><b>{track}</b><small>{playing?'Playing in this browser':'Paused'}</small></div></div>{message&&<p className="playback-message">{message}</p>}{error&&<p className="design-error">{error}</p>}<button className="browser-enable" onClick={()=>void enable()}>Enable audio</button><div className="browser-controls"><button onClick={()=>void localPlay()}><Play size={15}/> Play</button><button onClick={localPause}><Pause size={15}/> Pause</button><button onClick={localStop}><Square size={15}/> Stop</button><button onClick={()=>void heartbeat()}><RefreshCw size={15}/> Send heartbeat</button><button onClick={disconnect}><LogOut size={15}/> Disconnect</button></div><small>Leave this tab open. The manager can now use Playback for this player.</small></section></main>}
