import { useEffect, useState, type FormEvent } from 'react';
import { CalendarClock, Megaphone, Plus, Target, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/providers/AuthProvider';
import { useWorkspace } from '@/providers/WorkspaceProvider';

type CampaignRow={id:string;title:string;state:string;starts_at:string|null;ends_at:string|null;content_item_id:string|null;content_items:{title:string}|null;campaign_targets:{zone_id:string;audio_zones:{name:string;locations:{name:string}|null}|null}[]};
type Asset={id:string;title:string;state:string}; type Zone={id:string;name:string;locations:{name:string}|null};

export function CampaignsPage(){
 const {workspace}=useWorkspace();const {user}=useAuth();const [campaigns,setCampaigns]=useState<CampaignRow[]>([]);const [assets,setAssets]=useState<Asset[]>([]);const [zones,setZones]=useState<Zone[]>([]);const [loading,setLoading]=useState(true);const [show,setShow]=useState(false);const [message,setMessage]=useState('');const canManage=['owner','marketing'].includes(workspace?.role??'');
 const load=async()=>{if(!supabase||!workspace)return;setLoading(true);const [c,a,z]=await Promise.all([supabase.from('campaigns').select('id,title,state,starts_at,ends_at,content_item_id,content_items(title),campaign_targets(zone_id,audio_zones(name,locations(name)))').eq('organization_id',workspace.id).order('created_at',{ascending:false}),supabase.from('content_items').select('id,title,state').eq('organization_id',workspace.id).neq('state','archived').order('title'),supabase.from('audio_zones').select('id,name,locations(name)').order('name')]);if(c.error)setMessage(c.error.message);setCampaigns((c.data??[]) as unknown as CampaignRow[]);setAssets((a.data??[]) as Asset[]);setZones((z.data??[]) as unknown as Zone[]);setLoading(false);};
 useEffect(()=>{void load();},[workspace?.id]);
 if(!canManage)return <div style={page}><h1 style={title}>Campaigns</h1><p style={sub}>Only owners and marketing managers can manage campaigns.</p></div>;
 return <div style={page}><header style={header}><div><p style={eyebrow}>CAMPAIGN MANAGER</p><h1 style={title}>Campaigns</h1><p style={sub}>Turn audio assets into targeted branch moments.</p></div><button style={primary} onClick={()=>setShow(true)}><Plus size={16}/> New campaign</button></header>{message&&<div style={notice}>{message}<button onClick={()=>setMessage('')}><X size={15}/></button></div>}{loading?<p>Loading campaigns…</p>:campaigns.length===0?<div style={empty}><Megaphone size={30} color="var(--signal)"/><h2>No campaigns yet</h2><p>Create a campaign and target one or more audio zones.</p><button style={primary} onClick={()=>setShow(true)}>Create first campaign</button></div>:<div style={{display:'grid',gap:12}}>{campaigns.map(c=><article key={c.id} style={card}><div style={{display:'flex',justifyContent:'space-between',gap:14}}><div><h2 style={{margin:0,fontSize:17}}>{c.title}</h2><p style={meta}>{c.content_items?.title??'No asset selected'} · {c.campaign_targets?.length??0} target zone{c.campaign_targets?.length===1?'':'s'}</p></div><em style={stateBadge(c.state)}>{c.state}</em></div><div style={detailRow}><span><Target size={14}/> {c.campaign_targets?.map(t=>t.audio_zones?.locations?.name?(t.audio_zones.locations.name+' · '+t.audio_zones.name):t.audio_zones?.name).filter(Boolean).join(', ')||'No zones targeted'}</span><span><CalendarClock size={14}/> {c.starts_at?new Date(c.starts_at).toLocaleString():'Unscheduled'}</span></div></article>)}</div>}{show&&<CampaignModal userId={user?.id} organizationId={workspace?.id} assets={assets} zones={zones} onClose={()=>setShow(false)} onSaved={async()=>{setShow(false);await load();}} onError={setMessage}/>}</div>;
}

function CampaignModal({userId,organizationId,assets,zones,onClose,onSaved,onError}:{userId?:string;organizationId?:string;assets:Asset[];zones:Zone[];onClose:()=>void;onSaved:()=>Promise<void>;onError:(message:string)=>void}){
 const [title,setTitle]=useState('');const [assetId,setAssetId]=useState('');const [startsAt,setStartsAt]=useState('');const [endsAt,setEndsAt]=useState('');const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!supabase||!userId||!organizationId||!title.trim()||!assetId||selected.length===0){setError('Add a title, audio asset, and at least one target zone.');return;}setBusy(true);const c=await supabase.from('campaigns').insert({organization_id:organizationId,created_by:userId,title:title.trim(),content_item_id:assetId,starts_at:startsAt?new Date(startsAt).toISOString():null,ends_at:endsAt?new Date(endsAt).toISOString():null,state:startsAt?'scheduled':'draft'}).select('id').single();if(c.error||!c.data){setError(c.error?.message??'Could not create campaign.');setBusy(false);return;}const targets=await supabase.from('campaign_targets').insert(selected.map(zone_id=>({campaign_id:c.data.id,zone_id})));if(targets.error){await supabase.from('campaigns').delete().eq('id',c.data.id);setError(targets.error.message);setBusy(false);return;}await onSaved();};
 return <div style={overlay}><form style={modal} onSubmit={submit}><div style={modalHeader}><div><p style={eyebrow}>NEW CAMPAIGN</p><h2 style={{margin:'4px 0 0',fontSize:22}}>Create campaign</h2></div><button type="button" style={close} onClick={onClose}><X size={18}/></button></div><label style={label}>Campaign name<input style={field} required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Weekend brunch offer"/></label><label style={label}>Audio asset<select style={field} required value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">Select an asset</option>{assets.map(a=><option key={a.id} value={a.id}>{a.title} · {a.state}</option>)}</select></label><div style={twoCol}><label style={label}>Starts at<input style={field} type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label style={label}>Ends at<input style={field} type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></label></div><fieldset style={fieldset}><legend style={label}>Target audio zones</legend>{zones.length===0?<p style={meta}>Add a location and audio zone first.</p>:zones.map(z=><label key={z.id} style={checkRow}><input type="checkbox" checked={selected.includes(z.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,z.id]:current.filter(id=>id!==z.id))}/><span>{z.locations?.name?(z.locations.name+' · '):''}{z.name}</span></label>)}</fieldset>{error&&<p style={{color:'var(--danger)',fontSize:13}}>{error}</p>}<div style={modalActions}><button type="button" style={secondary} onClick={onClose}>Cancel</button><button style={primary} disabled={busy}>{busy?'Creating…':'Create campaign'}</button></div></form></div>;
}
const page={padding:'32px 40px',maxWidth:1200,margin:'0 auto'} as const;const header={display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16,flexWrap:'wrap',marginBottom:26} as const;const eyebrow={margin:0,color:'var(--signal)',fontWeight:600,fontSize:12,letterSpacing:'.06em'} as const;const title={margin:'5px 0',fontSize:28,color:'var(--ink)'} as const;const sub={margin:0,color:'var(--ink-secondary)'} as const;const primary={display:'inline-flex',alignItems:'center',gap:7,border:0,borderRadius:8,padding:'11px 14px',background:'var(--signal)',color:'#fff',fontWeight:600,cursor:'pointer'} as const;const secondary={border:'1px solid var(--border-color)',borderRadius:8,padding:'10px 14px',background:'#fff',color:'var(--ink)',cursor:'pointer'} as const;const card={background:'#fff',border:'1px solid var(--border-color)',borderRadius:14,padding:20} as const;const meta={margin:'7px 0 0',color:'var(--ink-secondary)',fontSize:13} as const;const detailRow={marginTop:18,display:'flex',flexWrap:'wrap',gap:18,color:'var(--ink-secondary)',fontSize:12} as const;const stateBadge=(state:string)=>({fontStyle:'normal',borderRadius:99,padding:'5px 9px',color:state==='active'?'var(--success)':'var(--signal)',background:state==='active'?'rgba(44,167,96,.10)':'rgba(244,124,44,.10)',fontSize:11} as const);const notice={display:'flex',justifyContent:'space-between',alignItems:'center',background:'rgba(210,63,63,.08)',color:'var(--danger)',borderRadius:9,padding:'10px 12px',marginBottom:16,fontSize:13} as const;const empty={background:'#fff',border:'1px dashed var(--border-color)',borderRadius:16,padding:42,textAlign:'center',color:'var(--ink-secondary)'} as const;const overlay={position:'fixed',inset:0,zIndex:300,background:'rgba(29,25,22,.52)',display:'grid',placeItems:'center',padding:20} as const;const modal={width:'min(620px,100%)',maxHeight:'90vh',overflowY:'auto',background:'#fff',borderRadius:16,padding:26,boxShadow:'var(--shadow-md)'} as const;const modalHeader={display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:12} as const;const close={border:0,background:'transparent',color:'var(--ink-secondary)',cursor:'pointer'} as const;const label={display:'block',fontSize:13,fontWeight:600,marginTop:15} as const;const field={width:'100%',marginTop:7,padding:'10px 11px',border:'1px solid var(--border-color)',borderRadius:8,font:'inherit',background:'#fff'} as const;const twoCol={display:'grid',gridTemplateColumns:'1fr 1fr',gap:12} as const;const fieldset={border:0,padding:0,margin:'14px 0 0'} as const;const checkRow={display:'flex',gap:9,alignItems:'center',padding:'9px 0',fontSize:13,color:'var(--ink-secondary)'} as const;const modalActions={display:'flex',justifyContent:'flex-end',gap:8,marginTop:22} as const;
