import { useCallback, useEffect, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, RefreshCw } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useWorkspace } from '@/providers/WorkspaceProvider';
import { useWorkspaceRealtime } from '@/hooks/useWorkspaceRealtime';
type Player = { id: string; display_name: string | null; state: string; last_seen_at: string | null; zone_id: string };
type Alert = { id: string; title: string; severity: string; state: string; details: string | null; created_at: string };
export function MonitoringPage() { const { workspace } = useWorkspace(); const [players, setPlayers] = useState<Player[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = useCallback(async () => { if (!supabase || !workspace) return; setLoading(true); const [p, a] = await Promise.all([supabase.from('players').select('id,display_name,state,last_seen_at,zone_id').order('state'), supabase.from('alerts').select('id,title,severity,state,details,created_at').neq('state', 'resolved').order('created_at', { ascending: false })]); setPlayers((p.data ?? []) as Player[]); setAlerts((a.data ?? []) as Alert[]); setError(p.error?.message ?? a.error?.message ?? ''); setLoading(false); }, [workspace?.id]); useEffect(() => { void load(); }, [load]); useWorkspaceRealtime(['players', 'alerts'], load); const online = players.filter(p => p.state === 'online').length; const attention = players.filter(p => p.state !== 'online').length; return <div style={page}><header style={header}><div><p style={eyebrow}>LIVE MONITORING</p><h1 style={title}>Monitoring</h1><p style={sub}>Updates refresh automatically when a player or alert changes.</p></div><button style={button} onClick={() => void load()}><RefreshCw size={15}/> Refresh</button></header>{error && <p style={{ color: 'var(--danger)' }}>{error}</p>}<div style={grid}><Metric icon={<CheckCircle2 size={18}/>} label="Online players" value={String(online)}/><Metric icon={<AlertTriangle size={18}/>} label="Needs attention" value={String(attention)}/><Metric icon={<Activity size={18}/>} label="Open alerts" value={String(alerts.length)}/></div>{loading ? <p>Loading monitoring data…</p> : <div style={columns}><section style={card}><h2 style={sectionTitle}>Player status</h2>{players.length === 0 ? <p style={sub}>No players are registered yet.</p> : players.map(p => <div style={row} key={p.id}><span><strong>{p.display_name || 'Unnamed player'}</strong><small>{p.last_seen_at ? `Last seen ${new Date(p.last_seen_at).toLocaleString()}` : 'No heartbeat yet'}</small></span><em style={badge(p.state)}>{p.state}</em></div>)}</section><section style={card}><h2 style={sectionTitle}>Open alerts</h2>{alerts.length === 0 ? <p style={sub}>No unresolved alerts.</p> : alerts.map(a => <div style={row} key={a.id}><span><strong>{a.title}</strong><small>{a.details || a.severity} · {new Date(a.created_at).toLocaleString()}</small></span><em style={badge(a.severity)}>{a.state}</em></div>)}</section></div>}</div>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div style={metric}><span style={metricIcon}>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></div>; }
const page = { padding: '32px 40px', maxWidth: 1200, margin: '0 auto' } as const; const header = { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16, flexWrap: 'wrap', marginBottom: 26 } as const; const eyebrow = { margin: 0, color: 'var(--signal)', fontWeight: 600, fontSize: 12, letterSpacing: '.06em' } as const; const title = { margin: '5px 0', fontSize: 28, color: 'var(--ink)' } as const; const sub = { margin: 0, color: 'var(--ink-secondary)' } as const; const button = { display: 'inline-flex', alignItems: 'center', gap: 7, border: '1px solid var(--border-color)', borderRadius: 8, padding: '10px 13px', background: '#fff', cursor: 'pointer' } as const; const grid = { display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 12, marginBottom: 22 } as const; const metric = { background: '#fff', border: '1px solid var(--border-color)', borderRadius: 12, padding: 16, display: 'flex', gap: 12, alignItems: 'center' } as const; const metricIcon = { width: 34, height: 34, display: 'grid', placeItems: 'center', borderRadius: 9, background: 'var(--surface-subtle)', color: 'var(--signal)' } as const; const columns = { display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 16 } as const; const card = { background: '#fff', border: '1px solid var(--border-color)', borderRadius: 14, padding: 20 } as const; const sectionTitle = { margin: '0 0 14px', fontSize: 17 } as const; const row = { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, padding: '13px 0', borderBottom: '1px solid var(--border-color)' } as const; const badge = (state: string) => ({ fontStyle: 'normal', borderRadius: 99, padding: '5px 9px', fontSize: 11, color: state === 'online' || state === 'resolved' ? 'var(--success)' : 'var(--danger)', background: state === 'online' || state === 'resolved' ? 'rgba(44,167,96,.10)' : 'rgba(210,63,63,.08)' }) as const;
