import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle } from 'lucide-react';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { Button } from '@/components/ui/Button';
import { supabase } from '@/lib/supabase';
import { useWorkspace } from '@/providers/WorkspaceProvider';
import { useWorkspaceRealtime } from '@/hooks/useWorkspaceRealtime';
type LocationData = { id: string; name: string; audio_zones: Array<{ id: string; name: string; players: Array<{ id: string; display_name: string | null; state: string; last_seen_at: string | null; device_code: string }> }> };
export function MyLocationPage() { const navigate = useNavigate(); const { workspace } = useWorkspace(); const [location, setLocation] = useState<LocationData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = useCallback(async () => { if (!supabase || !workspace) return; setLoading(true); let query = supabase.from('locations').select('id,name,audio_zones(id,name,players(id,display_name,state,last_seen_at,device_code))').eq('organization_id', workspace.id); if (workspace.locationId) query = query.eq('id', workspace.locationId); const result = await query.limit(1).maybeSingle(); setLocation(result.data as unknown as LocationData | null); setError(result.error?.message ?? ''); setLoading(false); }, [workspace?.id, workspace?.locationId]); useEffect(() => { void load(); }, [load]); useWorkspaceRealtime(['players', 'alerts'], load); if (loading) return <div style={page}>Loading your location…</div>; if (error) return <div style={page}><p style={{ color: 'var(--danger)' }}>{error}</p></div>; return <div style={page}><header style={header}><div><h1 style={title}>My location</h1><p style={sub}>{location?.name ?? 'No location assigned'}</p></div><Button variant="secondary" size="sm" onClick={() => navigate('/my-location/report-issue')} style={{ display: 'flex', gap: 6, alignItems: 'center' }}><AlertTriangle size={14}/> Report an issue</Button></header>{!location ? <section style={card}><p style={sub}>Your account has not been assigned to a location yet.</p></section> : <><section style={{ ...card, background: '#1A1410', border: 'none', color: '#fff', marginBottom: 24 }}><p style={{ color: 'rgba(255,255,255,.55)', fontSize: 12 }}>CURRENT LOCATION</p><h2 style={{ margin: '8px 0', fontSize: 22 }}>{location.name}</h2><p style={{ color: 'rgba(255,255,255,.65)', fontSize: 13 }}>{location.audio_zones.length} audio zone{location.audio_zones.length === 1 ? '' : 's'}</p></section><h2 style={sectionTitle}>Audio zones</h2><div className="zone-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 16 }}>{location.audio_zones.map(zone => { const player = zone.players[0]; const state = player?.state ?? 'unpaired'; return <section key={zone.id} style={card}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' }}><div><strong>{zone.name}</strong><p style={sub}>{player?.device_code ?? 'No player paired'}</p></div><StatusBadge status={state === 'online' ? 'Online' : state === 'unpaired' ? 'Not Paired' : 'Offline'} pulse={state === 'online'}/></div><p style={{ ...sub, marginTop: 16 }}>{player?.last_seen_at ? `Last seen ${new Date(player.last_seen_at).toLocaleString()}` : 'No heartbeat received yet.'}</p></section>; })}</div></>}</div>; }
const page = { padding: '32px 40px', maxWidth: 1000, margin: '0 auto' } as const; const header = { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 16, marginBottom: 28 } as const; const title = { margin: 0, fontSize: 28, fontWeight: 600 } as const; const sub = { margin: '6px 0 0', color: 'var(--ink-secondary)', fontSize: 13 } as const; const card = { background: 'var(--surface)', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)', padding: 22, boxShadow: 'var(--shadow-sm)' } as const; const sectionTitle = { margin: '0 0 16px', fontSize: 17 } as const;
