import { useCallback, useEffect, useState } from 'react';
import { Bell, Check, RefreshCw } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/providers/AuthProvider';
import { useWorkspace } from '@/providers/WorkspaceProvider';
import { useWorkspaceRealtime } from '@/hooks/useWorkspaceRealtime';
type Notification = { id: string; title: string; body: string; type: string; read_at: string | null; created_at: string };
const db = supabase as any;
export function NotificationsPage() { const { user } = useAuth(); const { workspace } = useWorkspace(); const [items, setItems] = useState<Notification[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = useCallback(async () => { if (!db || !user || !workspace) return; setLoading(true); const result = await db.from('notifications').select('id,title,body,type,read_at,created_at').eq('organization_id', workspace.id).or(`user_id.is.null,user_id.eq.${user.id}`).order('created_at', { ascending: false }).limit(50); setItems((result.data ?? []) as Notification[]); setError(result.error?.message ?? ''); setLoading(false); }, [workspace?.id, user?.id]); useEffect(() => { void load(); }, [load]); useWorkspaceRealtime(['notifications'], load); const markRead = async (id: string) => { const result = await db.from('notifications').update({ read_at: new Date().toISOString() }).eq('id', id).eq('user_id', user?.id); if (result.error) setError(result.error.message); else await load(); }; return <div style={page}><header style={header}><div><p style={eyebrow}>INBOX</p><h1 style={title}>Notifications</h1><p style={sub}>Alerts, player updates, campaign delivery, and support activity.</p></div><button style={button} onClick={() => void load()}><RefreshCw size={15}/> Refresh</button></header>{error && <p style={{ color: 'var(--danger)' }}>{error}</p>}<section style={card}>{loading ? <p style={sub}>Loading notifications…</p> : items.length === 0 ? <div style={empty}><Bell size={24}/><strong>You're all caught up</strong><span>New operational events will appear here.</span></div> : items.map(item => <article style={{ ...row, opacity: item.read_at ? .65 : 1 }} key={item.id}><span style={icon}><Bell size={16}/></span><div style={copy}><strong>{item.title}</strong><small>{item.body}</small><time>{new Date(item.created_at).toLocaleString()}</time></div>{!item.read_at && <button style={read} onClick={() => void markRead(item.id)}><Check size={14}/> Mark read</button>}</article>)}</section></div>; }
const page = { padding: '32px 40px', maxWidth: 1000, margin: '0 auto' } as const; const header = { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16, flexWrap: 'wrap', marginBottom: 26 } as const; const eyebrow = { margin: 0, color: 'var(--signal)', fontWeight: 600, fontSize: 12, letterSpacing: '.06em' } as const; const title = { margin: '5px 0', fontSize: 28 } as const; const sub = { margin: 0, color: 'var(--ink-secondary)' } as const; const button = { display: 'inline-flex', alignItems: 'center', gap: 7, border: '1px solid var(--border-color)', borderRadius: 8, padding: '10px 13px', background: '#fff', cursor: 'pointer' } as const; const card = { background: '#fff', border: '1px solid var(--border-color)', borderRadius: 14, padding: '8px 20px' } as const; const row = { display: 'flex', alignItems: 'center', gap: 12, padding: '15px 0', borderBottom: '1px solid var(--border-color)' } as const; const icon = { width: 32, height: 32, borderRadius: 9, display: 'grid', placeItems: 'center', color: 'var(--signal)', background: 'var(--surface-subtle)', flexShrink: 0 } as const; const copy = { display: 'grid', gap: 4, flex: 1 } as const; const read = { display: 'inline-flex', alignItems: 'center', gap: 5, border: '1px solid var(--border-color)', borderRadius: 7, padding: '7px 9px', background: '#fff', cursor: 'pointer', fontSize: 12 } as const; const empty = { display: 'grid', placeItems: 'center', gap: 8, padding: 48, color: 'var(--ink-secondary)', textAlign: 'center' } as const;
