import { useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { Building2, MapPin, Radio } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useWorkspace } from '@/providers/WorkspaceProvider';
export function OnboardingPage() {
  const nav=useNavigate(); const {refresh}=useWorkspace(); const [step,setStep]=useState(1);const [name,setName]=useState('');const [slug,setSlug]=useState('');const [location,setLocation]=useState('');const [zone,setZone]=useState('Main floor');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const createWorkspace=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setError('');const {data,error}=await supabase.functions.invoke('create-workspace',{body:{name,slug}});if(error||data?.error){setError(data?.error??error?.message??'Could not create workspace');setBusy(false);return;}await refresh();setBusy(false);setStep(2);};
  const createLocation=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setError('');await refresh();const {data:member}=await supabase.from('organization_members').select('organization_id').limit(1).single();const orgId=member?.organization_id;if(!orgId){setError('Workspace not found.');setBusy(false);return;}const {data:loc,error:locError}=await supabase.from('locations').insert({organization_id:orgId,name:location,code:location.toLowerCase().replace(/[^a-z0-9]+/g,'-')}).select().single();if(locError){setError(locError.message);setBusy(false);return;}const {data:z,error:zoneError}=await supabase.from('audio_zones').insert({location_id:loc.id,name:zone}).select().single();if(zoneError){setError(zoneError.message);setBusy(false);return;}await supabase.from('players').insert({zone_id:z.id,device_code:`BC-${crypto.randomUUID().slice(0,8).toUpperCase()}`,display_name:`${location} player`,state:'unpaired',pairing_code:crypto.randomUUID().slice(0,6).toUpperCase(),pairing_expires_at:new Date(Date.now()+15*60*1000).toISOString()});await supabase.from('organizations').update({onboarding_completed_at:new Date().toISOString()}).eq('id',orgId);setBusy(false);nav('/locations');};
  const item=(n:number,Icon:typeof Building2,label:string)=><div style={{display:'flex',gap:10,alignItems:'center',color:step>=n?'var(--ink)':'var(--ink-tertiary)',fontWeight:step===n?600:400}}><span style={{width:25,height:25,borderRadius:'50%',display:'grid',placeItems:'center',background:step>=n?'var(--signal)':'var(--surface-strong)',color:step>=n?'#fff':'var(--ink-secondary)',fontSize:12}}>{n}</span><Icon size={16}/>{label}</div>;
  return <div style={{minHeight:'100vh',background:'var(--canvas)',padding:'32px 24px'}}><div style={{maxWidth:880,margin:'0 auto'}}><div style={{fontSize:20,fontWeight:700}}>Branch<span style={{color:'var(--signal)'}}>Cast</span></div><div style={{display:'grid',gridTemplateColumns:'240px 1fr',gap:56,marginTop:72}}><aside style={{display:'flex',flexDirection:'column',gap:22}}>{item(1,Building2,'Your workspace')}{item(2,MapPin,'First location')}{item(3,Radio,'Ready to pair')}</aside><main style={{background:'#fff',border:'1px solid var(--border-color)',borderRadius:18,padding:34}}>{step===1?<form onSubmit={createWorkspace}><p style={{color:'var(--signal)',fontWeight:600,fontSize:13}}>STEP 1 OF 2</p><h1 style={{margin:'6px 0',fontSize:30}}>Name your workspace</h1><p style={{color:'var(--ink-secondary)'}}>This is the company your branches and team will belong to.</p><label style={{display:'block',fontWeight:600,fontSize:13,marginTop:24}}>Company name<input required value={name} onChange={e=>{setName(e.target.value);setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''))}} style={field}/></label><label style={{display:'block',fontWeight:600,fontSize:13,marginTop:16}}>Workspace URL<input required value={slug} onChange={e=>setSlug(e.target.value)} style={field}/><small style={{color:'var(--ink-tertiary)'}}>branchcast / {slug || 'your-company'}</small></label>{error&&<p style={{color:'var(--danger)',fontSize:13}}>{error}</p>}<button disabled={busy} style={primary}>{busy?'Creating…':'Continue'}</button></form>:<form onSubmit={createLocation}><p style={{color:'var(--signal)',fontWeight:600,fontSize:13}}>STEP 2 OF 2</p><h1 style={{margin:'6px 0',fontSize:30}}>Add your first location</h1><p style={{color:'var(--ink-secondary)'}}>You can add more branches and zones later.</p><label style={{display:'block',fontWeight:600,fontSize:13,marginTop:24}}>Location name<input required value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. Sweifieh branch" style={field}/></label><label style={{display:'block',fontWeight:600,fontSize:13,marginTop:16}}>First audio zone<input required value={zone} onChange={e=>setZone(e.target.value)} style={field}/></label>{error&&<p style={{color:'var(--danger)',fontSize:13}}>{error}</p>}<button disabled={busy} style={primary}>{busy?'Saving…':'Create location'}</button></form>}</main></div></div></div>;
}
const field={width:'100%',marginTop:7,padding:'11px 12px',border:'1px solid var(--border-color)',borderRadius:8,font:'inherit'} as const;
const primary={marginTop:24,border:0,borderRadius:8,padding:'12px 16px',background:'var(--signal)',color:'#fff',fontWeight:600,cursor:'pointer'} as const;
