import { useEffect, useMemo, useState } from 'react';
import { Pause, Play, Radio, Square, Volume2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useWorkspace } from '@/providers/WorkspaceProvider';
type Player={id:string;display_name:string|null;state:string;last_seen_at:string|null;active_content_item_id:string|null};type Asset={id:string;title:string;duration_seconds:number|null};
export function PlaybackRevamp(){const {workspace}=useWorkspace();const [players,setPlayers]=useState<Player[]>([]);const [assets,setAssets]=useState<Asset[]>([]);const [selected,setSelected]=useState('');const [playing,setPlaying]=useState(()=>localStorage.getItem('branchcast.playback-state')==='playing');const [message,setMessage]=useState('');const [error,setError]=useState('');const player=players.find(p=>p.id===selected)??players[0];const asset=assets.find(a=>a.id===player?.active_content_item_id)??assets[0];
 const load=async()=>{if(!workspace)return;const [p,a]=await Promise.all([(supabase as any).from('players').select('id,display_name,state,last_seen_at,active_content_item_id').order('display_name'),(supabase as any).from('content_items').select('id,title,duration_seconds').eq('organization_id',workspace.id).eq('state','ready').order('title')]);setPlayers((p.data??[]) as Player[]);setAssets((a.data??[]) as Asset[]);setSelected(current=>current||p.data?.[0]?.id||'')};useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer)},[workspace?.id]);
 const command=async(action:'play'|'pause'|'stop')=>{if(!player||player.state!=='online'){setError('Connect a browser player first.');return}setError('');const result=await (supabase as any).from('player_commands').insert({player_id:player.id,command:action,payload:action==='play'&&asset?{content_item_id:asset.id}:{},status:'pending'});if(result.error)setError(result.error.message);else{const next=action==='play';setPlaying(next);localStorage.setItem('branchcast.playback-state',next?'playing':'stopped');setMessage(`${action[0].toUpperCase()+action.slice(1)} command sent.`)}};
 const online=player?.state==='online';const progress=playing?48:0;const duration=asset?.duration_seconds?formatTime(asset.duration_seconds):'04:38';
 return <div className="design-page playback-revamp"><div className="playback-context"><span className="playback-live-dot"/> <span>{workspace?.name??'District 7'}</span><span>·</span><b>{player?.display_name??'Main floor'}</b><span className={online?'online-label':'offline-label'}>{online?'LIVE':'OFFLINE'}</span></div><header className="design-header"><div><p className="design-eyebrow">PLAYBACK</p><h1>Manager playback</h1><p>Control the current session and keep every branch in context.</p></div><label className="player-select">Player<select value={player?.id??''} onChange={e=>setSelected(e.target.value)}>{players.map(p=><option value={p.id} key={p.id}>{p.display_name??'Unnamed player'}</option>)}</select></label></header><div className="playback-grid"><section className="now-playing-card"><div className="card-kicker"><span>NOW PLAYING</span><span>{asset?'1 asset':'No asset'}</span></div><div className="now-playing-copy"><div className="album-art"><Radio size={24}/></div><div><h2>{asset?.title??'Manager playlist'}</h2><p>{asset?'Manager playlist · 1 active item':'Add a ready audio asset in Content first.'}</p></div></div><div className="progress-wrap"><div className="progress-track"><span style={{width:`${progress}%`}}/></div><div><span>{playing?'02:14':'00:00'}</span><span>{duration}</span></div></div><div className="playback-controls"><button onClick={()=>void command('play')} disabled={!online||!asset} className="primary-control"><Play size={17}/></button><button onClick={()=>void command('pause')} disabled={!online} className="control-button"><Pause size={17}/></button><button className="control-button"><Volume2 size={17}/></button><button onClick={()=>void command('stop')} disabled={!online} className="control-button"><Square size={15}/></button></div>{message&&<p className="playback-message">{message}</p>}{error&&<p className="design-error">{error}</p>}</section><aside className="playback-side"><section className="player-card"><div className="side-card-head"><div><p className="design-eyebrow">PLAYER</p><h3>{player?.display_name??'District 7'}</h3></div><span className={online?'live-pill':'offline-pill'}>{online?'LIVE':'OFFLINE'}</span></div><label>LOCATION<select><option>Main floor · 2 zones active</option></select></label><div className="side-controls"><button onClick={()=>void command('play')} disabled={!online||!asset}><Play size={15}/></button><button onClick={()=>void command('pause')} disabled={!online}><Pause size={15}/></button><button><Volume2 size={15}/></button><button onClick={()=>void command('stop')} disabled={!online}><Square size={14}/></button></div></section><section className="session-card"><p className="design-eyebrow">SESSION SUMMARY</p><Summary label="Player" value={player?.display_name??'District 7'}/><Summary label="Location" value="Main floor"/><Summary label="Playlist" value="Manager playlist"/><Summary label="Status" value={online?'LIVE':'OFFLINE'} accent={online}/></section></aside></div></div>}
function Summary({label,value,accent}:{label:string;value:string;accent?:boolean}){return <div className="summary-row"><span>{label}</span><b className={accent?'summary-live':''}>{value}</b></div>};const formatTime=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
