import { useEffect, useState } from 'react';
import { BarChart3, Download, FileAudio, Megaphone } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useWorkspace } from '@/providers/WorkspaceProvider';

export function ReportsPage() {
  const { workspace } = useWorkspace(); const [campaigns, setCampaigns] = useState(0); const [assets, setAssets] = useState(0); const [players, setPlayers] = useState(0); const [offline, setOffline] = useState(0);
  useEffect(() => { if (!supabase || !workspace) return; void Promise.all([supabase.from('campaigns').select('id',{count:'exact',head:true}).eq('organization_id',workspace.id),supabase.from('content_items').select('id',{count:'exact',head:true}).eq('organization_id',workspace.id),supabase.from('players').select('id,state').then(r => r)]).then(([c,a,p]) => { setCampaigns(c.count ?? 0); setAssets(a.count ?? 0); const rows=(p.data ?? []) as {state:string}[]; setPlayers(rows.length); setOffline(rows.filter(x=>x.state!=='online').length); }); }, [workspace?.id]);
  const exportCsv = () => { const csv='metric,value\\nCampaigns,'+campaigns+'\\nAudio assets,'+assets+'\\nPlayers,'+players+'\\nPlayers needing attention,'+offline; const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); const a=document.createElement('a'); a.href=url; a.download='branchcast-report.csv'; a.click(); URL.revokeObjectURL(url); };
  return <div style={page}><header style={header}><div><p style={eyebrow}>REPORTS</p><h1 style={title}>Reports & analytics</h1><p style={sub}>A simple operational snapshot for playback and campaigns.</p></div><button style={button} onClick={exportCsv}><Download size={15} /> Export CSV</button></header><div style={grid}><Metric icon={<Megaphone size={18}/>} label="Campaigns" value={String(campaigns)} /><Metric icon={<FileAudio size={18}/>} label="Audio assets" value={String(assets)} /><Metric icon={<BarChart3 size={18}/>} label="Players" value={String(players)} /><Metric icon={<BarChart3 size={18}/>} label="Needs attention" value={String(offline)} /></div><section style={card}><h2 style={sectionTitle}>Report coverage</h2><p style={sub}>Playback health is represented by online versus attention-needed players. Campaign delivery begins with campaign and asset inventory and can be extended with player event aggregation.</p></section></div>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div style={metric}><span style={metricIcon}>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></div>;}
const page={padding:'32px 40px',maxWidth:1200,margin:'0 auto'} as const;const header={display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16,flexWrap:'wrap',marginBottom:26} as const;const eyebrow={margin:0,color:'var(--signal)',fontWeight:600,fontSize:12,letterSpacing:'.06em'} as const;const title={margin:'5px 0',fontSize:28,color:'var(--ink)'} as const;const sub={margin:0,color:'var(--ink-secondary)'} as const;const button={display:'inline-flex',alignItems:'center',gap:7,border:'1px solid var(--border-color)',borderRadius:8,padding:'10px 13px',background:'#fff',cursor:'pointer'} as const;const grid={display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:12,marginBottom:22} as const;const metric={background:'#fff',border:'1px solid var(--border-color)',borderRadius:12,padding:16,display:'flex',gap:12,alignItems:'center'} as const;const metricIcon={width:34,height:34,display:'grid',placeItems:'center',borderRadius:9,background:'var(--surface-subtle)',color:'var(--signal)'} as const;const card={background:'#fff',border:'1px solid var(--border-color)',borderRadius:14,padding:20} as const;const sectionTitle={margin:'0 0 12px',fontSize:17} as const;
