import { useCallback, useEffect, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useWorkspace } from '@/providers/WorkspaceProvider';
import { useWorkspaceRealtime } from '@/hooks/useWorkspaceRealtime';
type Incident = { id: string; title: string; description: string | null; severity: string; status: string; created_at: string; resolution: string | null };
const db = supabase as any;
export function SupportIncidentsPage() { const { workspace } = useWorkspace(); const [items, setItems] = useState<Incident[]>([]); const [error, setError] = useState(''); const load = useCallback(async () => { if (!db || !workspace) return; const result = await db.from('support_incidents').select('id,title,description,severity,status,created_at,resolution').eq('organization_id', workspace.id).order('created_at', { ascending: false }); setItems((result.data ?? []) as Incident[]); setError(result.error?.message ?? ''); }, [workspace?.id]); useEffect(() => { void load(); }, [load]); useWorkspaceRealtime(['support_incidents'], load); const update = async (id: string, status: string) => { const result = await db.from('support_incidents').update({ status, updated_at: new Date().toISOString() }).eq('id', id); if (result.error) setError(result.error.message); else await load(); }; return <div style={page}><header style={header}><div><p style={eyebrow}>OPERATIONS</p><h1 style={title}>Support incidents</h1><p style={sub}>Assign, investigate, and close branch incidents.</p></div><button style={button} onClick={() => void load()}><RefreshCw size={15}/> Refresh</button></header>{error && <p style={{ color: 'var(--danger)' }}>{error}</p>}<section style={card}>{items.length === 0 ? <p style={sub}>No incidents have been reported.</p> : items.map(item => <article style={row} key={item.id}><div style={copy}><strong>{item.title}</strong><small>{item.description || 'No description'} · {new Date(item.created_at).toLocaleString()}</small></div><select value={item.status} onChange={e => void update(item.id, e.target.value)} style={select}><option>open</option><option>investigating</option><option>resolved</option><option>closed</option></select></article>)}</section></div>; }
const page = { padding: '32px 40px', maxWidth: 1000, margin: '0 auto' } as const; const header = { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16, flexWrap: 'wrap', marginBottom: 26 } as const; const eyebrow = { margin: 0, color: 'var(--signal)', fontWeight: 600, fontSize: 12, letterSpacing: '.06em' } as const; const title = { margin: '5px 0', fontSize: 28 } as const; const sub = { margin: 0, color: 'var(--ink-secondary)' } as const; const button = { display: 'inline-flex', alignItems: 'center', gap: 7, border: '1px solid var(--border-color)', borderRadius: 8, padding: '10px 13px', background: '#fff', cursor: 'pointer' } as const; const card = { background: '#fff', border: '1px solid var(--border-color)', borderRadius: 14, padding: '8px 20px' } as const; const row = { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 14, padding: '15px 0', borderBottom: '1px solid var(--border-color)' } as const; const copy = { display: 'grid', gap: 5, flex: 1 } as const; const select = { border: '1px solid var(--border-color)', borderRadius: 8, padding: '8px 10px', background: '#fff' } as const;
