import { useEffect, useState } from 'react';
import { Mail, Plus, Shield } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useWorkspace } from '@/providers/WorkspaceProvider';
import { useAuth } from '@/providers/AuthProvider';

type Member={user_id:string;role:string;location_id:string|null};
export function TeamPage(){const {workspace}=useWorkspace();const {user}=useAuth();const [members,setMembers]=useState<Member[]>([]);const [email,setEmail]=useState('');const [role,setRole]=useState<'marketing'|'operations'|'branch'|'viewer'>('marketing');const [message,setMessage]=useState('');const load=async()=>{if(!supabase||!workspace)return;const {data}=await supabase.from('organization_members').select('user_id,role,location_id').eq('organization_id',workspace.id);setMembers((data??[]) as Member[]);};useEffect(()=>{void load();},[workspace?.id]);const invite=async()=>{if(!supabase||!workspace||!user||!email.trim()){setMessage('Enter an email address.');return;}const {error}=await supabase.from('workspace_invites').insert({organization_id:workspace.id,created_by:user.id,email:email.trim(),role});setMessage(error?.message??'Invite created.');if(!error)setEmail('');};return <div style={page}><header style={header}><div><p style={eyebrow}>ORGANIZATION</p><h1 style={title}>Team & roles</h1><p style={sub}>Manage who can operate this workspace.</p></div></header><section style={card}><h2 style={sectionTitle}>Invite member</h2><div style={form}><input style={field} placeholder="person@company.com" value={email} onChange={e=>setEmail(e.target.value)} /><select style={field} value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="marketing">Marketing</option><option value="operations">Operations</option><option value="branch">Branch manager</option><option value="viewer">Viewer</option></select><button style={primary} onClick={()=>void invite()}><Plus size={15}/> Invite</button></div>{message&&<p style={sub}>{message}</p>}</section><section style={card}><h2 style={sectionTitle}>Current members</h2>{members.map(m=><div style={row} key={m.user_id}><span><Shield size={15}/> {m.user_id}</span><em>{m.role}</em></div>)}</section></div>;}
const page={padding:'32px 40px',maxWidth:1000,margin:'0 auto'} as const;const header={marginBottom:26} as const;const eyebrow={margin:0,color:'var(--signal)',fontWeight:600,fontSize:12,letterSpacing:'.06em'} as const;const title={margin:'5px 0',fontSize:28} as const;const sub={margin:0,color:'var(--ink-secondary)'} as const;const card={background:'#fff',border:'1px solid var(--border-color)',borderRadius:14,padding:20,marginBottom:16} as const;const sectionTitle={margin:'0 0 14px',fontSize:17} as const;const form={display:'grid',gridTemplateColumns:'2fr 1fr auto',gap:9} as const;const field={padding:'10px 11px',border:'1px solid var(--border-color)',borderRadius:8,font:'inherit'} as const;const primary={display:'inline-flex',alignItems:'center',gap:7,border:0,borderRadius:8,padding:'10px 14px',background:'var(--signal)',color:'#fff',fontWeight:600,cursor:'pointer'} as const;const row={display:'flex',justifyContent:'space-between',padding:'12px 0',borderBottom:'1px solid var(--border-color)'} as const;
